export const styles = {
  main: {
    position: "relative",
    zIndex: 50,
    fontFamily: data?.design?.font_family || "Helvetica",
  },
  openButton: {
    position: "fixed",
    bottom: "2.5rem",
    right: "2.5rem",
    borderRadius: "4px",
    height: "5rem",
    width: "5rem",
    backgroundColor: data?.design?.widget_button_color || "#90cdf4",
    padding: "0.75rem",
  },
  wrapper: {
    backgroundImage:
      `url(${data?.design?.background_image})` ||
      "url(https://source.unsplash.com/user/c_v_r/1900x800)",
    backgroundSize: "100% 60%",
    backgroundRepeat: "no-repeat",
    backgroundColor: data?.design?.background_color || "#527B97",
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "0.25rem",
    borderWidth: "1px",
    borderColor: "#527B97",
    width: "23.938rem",
    minHeight: "18.063rem",
    height: "25.063rem",
  },
  upperSection: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    justifyContent: "center",
    alignItems: "center",
    color: "#ffffff",
    height: "60%",
  },
  upperSection_name: {
    fontSize: "0.806rem",
    fontWeight: "600",
  },
  upperSection_title: {
    textAlign: "center",
    color: data?.design?.title_color || "black",
    fontWeight: 700,
    fontSize: "1.13rem",
    width: "60%",
  },
  upperSection_subtitle: {
    textAlign: "center",
    color: data?.design?.sub_text_color || "black",
    fontWeight: 600,
    fontSize: "0.95rem",
    width: "70%",
  },
  upperSection_subtitle_span: {
    color: "0.888rem",
    fontWeight: 400,
  },
  lowerSection: {
    display: "flex",
    paddingTop: "0.5rem",
    paddingBottom: "0.5rem",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    backgroundColor: data?.design?.widget_button_color || "#ffffff",
    height: "40%",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: data?.design?.form_background_color || "#ffffff",
    borderRadius: "0.25rem",
    borderWidth: "1px",
    padding: "0.5rem",
    zIndex: 10,
    fontSize: "0.875rem",
    gap: "0.25rem",
    lineHeight: "1.25rem",
    boxShadow:
      "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
    width: "80%",
  },
  form_submitButton: {
    background: data?.design?.form_button_color || "#ffffff",
    color: data?.design?.form_text_color || "black",
    fontSize: "11px",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    borderRadius: "0.25rem",
  },
  form_label: {
    fontSize: "11px",
  },
  form_input: {
    borderRadius: "0.25rem",
    borderWidth: "1px",
    borderColor: "#9CA3AF",
    outlineStyle: "none",
  },
};
